### ISSUE TITLE
请问哪里可以找到当前项目的mongodb数据库

### ISSUE THREAD

**Issue by wszwj** [Ma63d/kov-blog#10]
请问哪里可以找到当前项目的mongodb数据库？
thx

**Comment by Ma63d** [comment]
你的mongodb数据库里的`kov-blog-dev`数据库是测试环境下的数据库
生产环境下用到的数据库是`kov-blog`

**Comment by Ma63d** [comment]
在server/configs/ 目录下有两个配置文件index.js和dev.js，在里面进行你mongodb数据库的配置，
比如在index.js文件里就有如下配置：
```javascript
mongoConfig: { // 数据库配置
    url: 'mongodb://localhost:27017/kov-blog',
    opts:{
      user:'',
      pass:''
    }
  },
```

dev的话配置文件是用的dev.js 里面指定的数据库是mongodb://localhost:27017/kov-blog-dev

生产环境使用的index.js的配置，开发环境用的是dev.js的配置
