### ISSUE TITLE
后台管理界面点击增加文章报错

### ISSUE THREAD

**Issue by wszwj** [Ma63d/kov-blog#11]
错误提示为：
localhost:3000/api/drafts 500(Internal Server Error)

**Comment by Ma63d** [comment]
那麻烦把server/logs目录下的今天的目录日志也贴出来 我帮你看看哪错了

**Comment by wszwj** [comment]
server error TypeError: Unknown encoding: 1
    at Buffer.slowToString (buffer.js:512:17)
    at Buffer.toString (buffer.js:525:27)
    at ObjectID.toString (E:\web\测试\kov-blog-master\node_modules\bson\lib\bson\objectid.js:174:20)
    at formatValue (util.js:297:21)
    at formatProperty (util.js:722:15)
    at util.js:582:12
    at Array.map (native)
    at formatObject (util.js:581:15)
    at formatValue (util.js:520:16)
    at Object.inspect (util.js:147:10)
    at Function.exports.formatters.O (E:\web\测试\kov-blog-master\node_modules\debug\src\node.js:96:15)
    at E:\web\测试\kov-blog-master\node_modules\debug\src\debug.js:101:27
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.debug (E:\web\测试\kov-blog-master\node_modules\debug\src\debug.js:94:23)
    at draftArr.forEach (E:\web\测试\kov-blog-master\server\controllers\draft.js:79:13)

{"request":{"method":"GET","url":"/api/drafts","header":{"host":"localhost:3000","connection":"keep-alive","accept":"application/json","origin":"http://localhost:8081","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ODZlMmQxYmFkZmRmNjA2ZWNlNGU5NGQiLCJuYW1lIjoiYWRtaW4iLCJleHAiOjE0ODM3NTY0MTUsImlhdCI6MTQ4MzY3MDAxNX0.sFIGi599o90AfOrdBedGAQwso13LPMN4iWD34orrXGA","referer":"http://localhost:8081/","accept-encoding":"gzip, deflate, sdch, br","accept-language":"zh-CN,zh;q=0.8","cookie":"_ga=GA1.1.1802474863.1483451055"}},"response":{"status":404,"message":"Not Found","header":{"access-control-allow-origin":"http://localhost:8081","access-control-max-age":"604800","access-control-allow-credentials":"true","access-control-allow-methods":"GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE","access-control-allow-headers":"Content-Type, Accept, Authorization"}},"app":{"subdomainOffset":2,"proxy":false,"env":"production "},"originalUrl":"/api/drafts","req":"<original node req>","res":"<original node res>","socket":"<original node socket>"}

**Comment by Ma63d** [comment]
@wszwj  找到错误原因了！
看了下错误 我在[draft.js的79行](https://github.com/Ma63d/kov-blog/blob/master/server/controllers/draft.js#L79)里写了一句:
```
utils.print(draft); 
```
这句会把从数据库里查出来的draft对象打印出来，但是打印出来的时候报错：TypeError: Unknown encoding: 

原因是这个draft对象的ObjectId竟然打印不出来，Unknown encoding
我在我本机测试没问题
然后google了下，发现别人也有相同的情况，ObjectId打印不出来：http://stackoverflow.com/questions/41457176/getting-typeerror-unknown-encoding-1-while-running-the-server-script-with-mong
也就是在这个连接里面提到这个bug是`bson`这个库的问题， 参见此issue：https://github.com/Automattic/mongoose/issues/4864

跟你的错误一模一样，

解决方法是把`bson`这个npm库给升级到1.0.3，这是前几天才出现的bug。

**Comment by Ma63d** [comment]
`bson`不是我依赖的库，
直接升级mongoose比较简单:
```bash
#输入这行命令应该可以解决你的问题了
npm update mongoose
```
