### ISSUE TITLE
请问，我想把贵博客管理系统修改成一个 支持文章 测评 新闻 增删查改  管理员 对用户进行权限的系统 有什么好建议吗

### ISSUE THREAD

**Issue by wszwj** [Ma63d/kov-blog#12]
请问，我想把贵博客管理系统修改成一个 支持文章 测评 新闻 增删查改  管理员 对用户进行权限的系统 有什么好建议吗

**Comment by Ma63d** [comment]
我的建议是重新写一个，你花时间去读我的代码然后再改，成本有点高，效率可能不如你直接上手写。
本身这个博客的功能其实不多，从头写的话不会超过3周的。
