### ISSUE TITLE
老哥，方便分享一下你的nginx的配置文件吗？

### ISSUE THREAD

**Issue by jo0ger** [Ma63d/kov-blog#13]
我现在正在想把自己的项目部署到nginx服务器上，但是有一个问题，在单页应用的某个页面重新刷新一下页面，nginx会返回404，肯定是配置没配好，刚开始用nginx，想瞅瞅你的nginx配置是怎么弄的

**Comment by Ma63d** [comment]
> 在单页应用的某个页面重新刷新一下页面，nginx会返回404

老哥 你这个是不是开了vue-router 2的HTML5 History 模式啊？
所以你的链接是不是这样的： you.com/a/b/c

**Comment by jo0ger** [comment]
确实是开了history，这个有招解决吗

**Comment by Ma63d** [comment]
那必然有啊 
location / {
  try_files $uri $uri/ /index.html;
}
