### ISSUE TITLE
打开新的文章，焦点会跳转到文章中间部分

### ISSUE THREAD

**Issue by madneal** [Ma63d/kov-blog#15]
每次从博文链接中打开一篇新文章，焦点就会自动跳转到文章中间部分，如果刷新一遍，就会跳转到头部。我看了一下，貌似链接里面也没有id的定位，不知道这是一个BUG还是你故意的设计？

**Comment by Ma63d** [comment]
这确实是个之前就注意到的bug。
不好意思，最近在准备找暑期实习，忙完这段时间会去de掉这个bug。
