### ISSUE TITLE
请问服务器端应该如何配置？如何运行？

### ISSUE THREAD

**Issue by Cheese-Yu** [Ma63d/kov-blog#16]
是直接把打包后的文件丢到服务器上，然后node run 哪些东西呢？需要具体修改什么配置吗？小白白，求指导~谢谢

**Comment by Ma63d** [comment]
对于client和admin，都是打包好扔服务器即可。
server是需要一个node跑着./server/index.js，node .server/index.js就能让server跑起来，你应该借助pm2等工具让.server/index.js始终跑在服务器上。
同时server可能需要配一下你自己mongodb的端口、用户名密码什么的。详见server/configs/index.js。

**Comment by Cheese-Yu** [comment]
谢谢~
