### ISSUE TITLE
没有开源协议

### ISSUE THREAD

**Issue by han1475** [Ma63d/kov-blog#18]
你好：
     首先感谢你开源的项目，我目前基于这个项目在做自己的在线学习网站，你的项目现在没有选择任何开源协议，请问我该怎样处理版权问题？近期是否有添加开源协议的计划？谢谢。

**Comment by Ma63d** [comment]
额。。忘了，已加MIT license.

**Comment by han1475** [comment]
好的，已按照MIT协议保留你的许可协议，由于一些原因没有使用Fork，谢谢。

**Comment by Ma63d** [comment]
@hanxiaojun  好的。
