### ISSUE TITLE
目录按钮不起作用

### ISSUE THREAD

**Issue by han1475** [Ma63d/kov-blog#19]
我的环境是node v7.4.0，fedora 24 x86_64 workstation，chrome浏览，未做任何改动，直接运行。
目录按钮点击没反应，查看源码为空的div，尝试切换到刚刚提交回到顶部和目录的commit仍一样的表现。
内容写作使用#作为标题标记,是我哪里用错了吗？谢谢。

**Comment by Ma63d** [comment]
你的文章有内容吗？ 或者说你内容没有超过一页？ 没有超过一页那就已经在视口以内，当然不会跳转。

**Comment by han1475** [comment]
文章有内容，并且超过一页，node切换到v6.10.2也是一样的问题。谢谢，我按照你的环境再试一次吧，比如node版本，你用的多少，谢谢。

**Comment by han1475** [comment]
补充：问题是目录按钮没有反应，不会弹出目录。另外，如果是我自己出现该问题，该项目确认无误的话，我会尝试其他实现方式，非常感谢。

**Comment by Ma63d** [comment]
你在我的博客上 chuckliu.me 能点开目录吗？

这个是纯前端实现。跟node版本没关系

**Comment by han1475** [comment]
已确认，能点开。

**Comment by Ma63d** [comment]
那你估计得debug一下了。我在本地环境和线上我的博客项目都没有问题。

**Comment by han1475** [comment]
你的博客标题是使用什么markdown 语法写的，我怀疑是我标题使用错误，导致无法扫描目录。劳烦给个示例语法的文章。好的，

**Comment by Ma63d** [comment]
博客标题？  博客的标题不就是一行纯文本吗？
博客的内容才是markdown啊，markdown只有一种语法啊。

**Comment by han1475** [comment]
已经解决了，我把Catalog.vue里的```addHeaderToArr(result, doms, 0, 2)```改为```addHeaderToArr(result, doms, 0, 1)```我的目录就完全正常了。
