### ISSUE TITLE
如图kov-blog项目启不起来

### ISSUE THREAD

**Issue by PuRonglong** [Ma63d/kov-blog#22]
![image](https://user-images.githubusercontent.com/8725006/28828068-2cf93da8-7702-11e7-8071-8010e5a8654c.png)

**Comment by Ma63d** [comment]
你是用的是哪个代码分支？

**Comment by PuRonglong** [comment]
@Ma63d 你好，我用的master分支，开发和部署应该分别用哪个分支，v2分支是否已改造完呢？

**Comment by Ma63d** [comment]
好的，我明天看看 master。
最近实在是抽不出时间升级，v2 分支目前只改造了后端和 admin 部分，但是只是技术栈升级和代码重构，想加的好多功能还没有加完。v2 预计会在9月份重启。

**Comment by Ma63d** [comment]
这个是前端跨域的问题，简单看了下 master 分支有用 koa-cors 跨域。我明天再 debug 看看。

**Comment by PuRonglong** [comment]
:smiley:,好的，vue2版我本来想clone下来看看源码然后修改的呢，然后今天看到有个v2分支，才知道楼主已经在进行中了，不知道开发到什么进度的就问下，哈哈，可是后台之前用的express没用过koa的，得先熟悉熟悉koa。。。

**Comment by PuRonglong** [comment]
@Ma63d 报告楼主，我重新启动了那3个npm run指令，项目可以启起来了，可能是我之前没有都npm run一遍所以起不起来，应该是我的问题，现在OK了。
