### ISSUE TITLE
关于kov-blog的UI设计

### ISSUE THREAD

**Issue by StudentWan** [Ma63d/kov-blog#23]
学长好。
我看了您的个人blog项目觉得很喜欢，也很适合作为练手项目，于是准备自己实现一个blog，做到UI设计这一块有点懵，不知道该怎么去设计这个应用...不知道学长在完成kov-blog的UI设计时有什么心得可以分享吗？
如果有的话就太感谢啦！

**Comment by Ma63d** [comment]
额。。。
并没有任何设计方面的心得，自己的审美也很不咋地，所以如果是自己设计的话那整个网页就无法直视了。
网页直接使用了Vue官网的样式，https://github.com/vuejs/cn.vuejs.org

**Comment by StudentWan** [comment]
我也...在前端沿用了学长的样式...
admin端自己搞了搞
