### ISSUE TITLE
npm run build-admin的时候有warning

### ISSUE THREAD

**Issue by davidcaiyou** [Ma63d/kov-blog#4]
npm run build-admin的时候有warning如下图

![image](https://cloud.githubusercontent.com/assets/2617354/19262041/5902c34c-8fc7-11e6-94aa-177293c3c15c.png)

**Comment by Ma63d** [comment]
之前用simplemde这个库的时候报错:Module not found: Error: Cannot resolve module 'fs'
可是fs明明是后端的自带库,前端不应该用这个,
但是直接用打包好的代码就不会有问题，所以就直接用了打包好的min.js。
不过刚刚查了一下，按照这个[issue](https://github.com/NextStepWebs/simplemde-markdown-editor/issues/358)说的解决了问题，现在webpack已经不会报warning了。
